@echo off
title START ECOM EYES ALL
cd /d D:\ECOM_GOVERNED_RUNTIME
echo ==== START ECOM EYES ALL ====
echo MODE=LOCAL_WINDOWS_ONLY_NO_SERVER_WRITE_NO_EBAY_NO_RESTART
echo.
echo STEP 1 - CHECK NGROK
where ngrok
ngrok version
echo.
echo STEP 2 - START SERVER EYES BRIDGE
start /min "SERVER EYES BRIDGE" cmd /k call "D:\ECOM_GOVERNED_RUNTIME\ION_LOCAL_ASSISTANT\launchers_internal\SERVER EYES BRIDGE.cmd"
echo.
echo STEP 3 - WAIT 40 SECONDS FOR LOCAL MCP 18765
timeout /t 40 /nobreak
echo.
echo STEP 4 - START NGROK HTTP 18765
start /min "ECOM SERVER EYES NGROK" cmd /k ngrok http 18765
echo.
echo STEP 5 - WAIT 8 SECONDS FOR NGROK
timeout /t 8 /nobreak
echo DECISION=PASS_STARTED_ECOM_EYES_ALL> "D:\ECOM_GOVERNED_RUNTIME\NGROK_EYES_STATUS.txt"
echo EXPECTED_MCP_URL=https://bottling-underwear-jaunt.ngrok-free.dev/mcp>> "D:\ECOM_GOVERNED_RUNTIME\NGROK_EYES_STATUS.txt"
echo CHATGPT_APP=ECOM Server Direct Eyes NGROK>> "D:\ECOM_GOVERNED_RUNTIME\NGROK_EYES_STATUS.txt"
curl.exe -s http://127.0.0.1:4040/api/tunnels > "D:\ECOM_GOVERNED_RUNTIME\NGROK_EYES_TUNNELS.json"
echo.
echo ==== STATUS ====
type "D:\ECOM_GOVERNED_RUNTIME\NGROK_EYES_STATUS.txt"
echo.
echo DECISION=PASS_STARTED_SERVER_EYES_BRIDGE_AND_NGROK
echo KEEP OPEN MINIMIZED: SERVER EYES BRIDGE and ECOM SERVER EYES NGROK
echo USE CHATGPT APP: ECOM Server Direct Eyes NGROK
pause
exit /b 0
